# CatBoost

## Importing the library

In [1]:
import numpy as np
import pandas as pd
import os.path

## Load the dataset

In [2]:
raw_data_file_path = '/Users/vishalsaxena/Documents/DS_Workspace/udemy_ml_algo_python/data/raw/'
dataset = pd.read_csv(os.path.join(raw_data_file_path, 'breast-cancer.csv'))
dataset

Sample code number  Clump Thickness  Uniformity of Cell Size  \
0               1000025                5                        1   
1               1002945                5                        4   
2               1015425                3                        1   
3               1016277                6                        8   
4               1017023                4                        1   
..                  ...              ...                      ...   
678              776715                3                        1   
679              841769                2                        1   
680              888820                5                       10   
681              897471                4                        8   
682              897471                4                        8   

     Uniformity of Cell Shape  Marginal Adhesion  Single Epithelial Cell Size  \
0                           1                  1                            2   
1                           4                  5                            7   
2                           1                  1                            2   
3                           8                  1                            3   
4                           1                  3                            2   
..                        ...                ...                          ...   
678                         1                  1                            3   
679                         1                  1                            2   
680                        10                  3                            7   
681                         6                  4                            3   
682                         8                  5                            4   

     Bare Nuclei  Bland Chromatin  Normal Nucleoli  Mitoses  Class  
0              1                3                1        1      2  
1             10                3                2        1      2  
2              2                3                1        1      2  
3              4                3                7        1      2  
4              1                3                1        1      2  
..           ...              ...              ...      ...    ...  
678            2                1                1        1      2  
679            1                1                1        1      2  
680            3                8               10        2      4  
681            4               10                6        1      4  
682            5               10                4        1      4  

[683 rows x 11 columns]

## Drop the irrelevant column

In [3]:
dataset = dataset.drop(columns=['Sample code number'])
dataset

Clump Thickness  Uniformity of Cell Size  Uniformity of Cell Shape  \
0                  5                        1                         1   
1                  5                        4                         4   
2                  3                        1                         1   
3                  6                        8                         8   
4                  4                        1                         1   
..               ...                      ...                       ...   
678                3                        1                         1   
679                2                        1                         1   
680                5                       10                        10   
681                4                        8                         6   
682                4                        8                         8   

     Marginal Adhesion  Single Epithelial Cell Size  Bare Nuclei  \
0                    1                            2            1   
1                    5                            7           10   
2                    1                            2            2   
3                    1                            3            4   
4                    3                            2            1   
..                 ...                          ...          ...   
678                  1                            3            2   
679                  1                            2            1   
680                  3                            7            3   
681                  4                            3            4   
682                  5                            4            5   

     Bland Chromatin  Normal Nucleoli  Mitoses  Class  
0                  3                1        1      2  
1                  3                2        1      2  
2                  3                1        1      2  
3                  3                7        1      2  
4                  3                1        1      2  
..               ...              ...      ...    ...  
678                1                1        1      2  
679                1                1        1      2  
680                8               10        2      4  
681               10                6        1      4  
682               10                4        1      4  

[683 rows x 10 columns]

## Segregate independent and dependent variable

In [4]:
X = dataset.iloc[:,:-1].values
X

array([[ 5,  1,  1, ...,  3,  1,  1],
       [ 5,  4,  4, ...,  3,  2,  1],
       [ 3,  1,  1, ...,  3,  1,  1],
       ...,
       [ 5, 10, 10, ...,  8, 10,  2],
       [ 4,  8,  6, ..., 10,  6,  1],
       [ 4,  8,  8, ..., 10,  4,  1]], shape=(683, 9))

In [5]:
y = dataset.iloc[:,-1].values
y

array([2, 2, 2, 2, 2, 4, 2, 2, 2, 2, 2, 2, 4, 2, 4, 4, 2, 2, 4, 2, 4, 4,
       2, 2, 4, 2, 2, 2, 2, 2, 2, 4, 2, 2, 2, 4, 2, 4, 4, 4, 4, 4, 4, 2,
       4, 2, 2, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 2, 4, 4, 2, 4, 2, 4,
       4, 2, 2, 4, 2, 4, 4, 2, 2, 2, 2, 2, 2, 2, 2, 2, 4, 4, 4, 4, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 4, 4, 4, 4, 2, 4, 4, 4, 4, 4, 2, 4, 2, 4,
       4, 4, 2, 2, 2, 4, 2, 2, 2, 2, 4, 4, 4, 2, 4, 2, 4, 2, 2, 2, 4, 2,
       2, 2, 2, 2, 2, 2, 2, 4, 2, 2, 4, 2, 2, 4, 2, 4, 4, 2, 2, 4, 2, 2,
       4, 4, 2, 2, 2, 2, 4, 4, 2, 2, 2, 2, 2, 4, 4, 4, 2, 4, 2, 4, 2, 2,
       2, 4, 4, 2, 4, 4, 4, 2, 4, 4, 2, 2, 2, 2, 2, 2, 2, 2, 4, 4, 2, 2,
       2, 4, 4, 2, 2, 2, 4, 4, 2, 4, 4, 4, 2, 2, 4, 2, 2, 4, 4, 4, 4, 2,
       4, 4, 2, 4, 4, 4, 2, 4, 2, 4, 4, 4, 4, 2, 2, 2, 2, 2, 2, 4, 4, 2,
       2, 4, 2, 4, 4, 4, 2, 2, 2, 2, 4, 4, 4, 4, 4, 2, 4, 4, 4, 2, 4, 2,
       4, 4, 2, 2, 2, 2, 4, 2, 2, 4, 4, 4, 4, 4, 2, 4, 4, 2, 2, 4, 4, 2,
       2, 4, 4, 2, 4, 2, 4, 4, 2, 2, 4, 2, 2, 2, 4,

In [6]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
y = encoder.fit_transform(y)
y

array([0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0,
       1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0,
       0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0,
       1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0,
       0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1,

## Splitting the dataset in Train/Test split

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)
X_train, X_test

(array([[10,  1,  1, ...,  5,  4,  1],
        [ 1,  1,  1, ...,  3,  1,  1],
        [ 5,  1,  1, ...,  3,  1,  1],
        ...,
        [ 1,  1,  1, ...,  1,  1,  1],
        [ 3,  1,  1, ...,  2,  1,  1],
        [10,  9,  7, ...,  7,  7,  1]], shape=(546, 9)),
 array([[ 1,  1,  1, ...,  1,  1,  1],
        [ 3,  1,  1, ...,  2,  1,  1],
        [ 5,  5,  5, ...,  4,  3,  1],
        ...,
        [ 4,  1,  1, ...,  1,  1,  1],
        [ 4, 10,  4, ...,  9, 10,  1],
        [ 2,  1,  1, ...,  2,  1,  1]], shape=(137, 9)))

In [8]:
y_train, y_test

(array([1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0,
        1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1,
        1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
        0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1,
        1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0,
        1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0,
        0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0,
        0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0,
        0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1,
        1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0,
        1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0,
        0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 

## Training XGBoost on the training set

In [9]:
from catboost import CatBoostClassifier
classifier = CatBoostClassifier()
classifier.fit(X_train, y_train)

Learning rate set to 0.007956
0:	learn: 0.6773046	total: 57.1ms	remaining: 57s
1:	learn: 0.6597974	total: 57.4ms	remaining: 28.7s
2:	learn: 0.6444870	total: 57.8ms	remaining: 19.2s
3:	learn: 0.6292695	total: 58.2ms	remaining: 14.5s
4:	learn: 0.6167805	total: 58.6ms	remaining: 11.7s
5:	learn: 0.6006774	total: 59ms	remaining: 9.78s
6:	learn: 0.5863012	total: 59.4ms	remaining: 8.43s
7:	learn: 0.5719487	total: 59.8ms	remaining: 7.42s
8:	learn: 0.5584160	total: 60.2ms	remaining: 6.63s
9:	learn: 0.5444027	total: 60.6ms	remaining: 6s
10:	learn: 0.5324566	total: 60.9ms	remaining: 5.48s
11:	learn: 0.5230006	total: 61.2ms	remaining: 5.04s
12:	learn: 0.5107660	total: 61.6ms	remaining: 4.67s
13:	learn: 0.4993511	total: 61.9ms	remaining: 4.36s
14:	learn: 0.4890182	total: 62.3ms	remaining: 4.09s
15:	learn: 0.4798579	total: 62.6ms	remaining: 3.85s
16:	learn: 0.4688945	total: 62.9ms	remaining: 3.64s
17:	learn: 0.4603258	total: 63.3ms	remaining: 3.45s
18:	learn: 0.4500329	total: 63.7ms	remaining: 3.29s

426:	learn: 0.0321282	total: 192ms	remaining: 258ms
427:	learn: 0.0320523	total: 193ms	remaining: 257ms
428:	learn: 0.0319740	total: 193ms	remaining: 257ms
429:	learn: 0.0318741	total: 193ms	remaining: 256ms
430:	learn: 0.0317971	total: 193ms	remaining: 255ms
431:	learn: 0.0317438	total: 194ms	remaining: 255ms
432:	learn: 0.0316463	total: 194ms	remaining: 254ms
433:	learn: 0.0315493	total: 194ms	remaining: 253ms
434:	learn: 0.0314618	total: 195ms	remaining: 253ms
435:	learn: 0.0314036	total: 195ms	remaining: 252ms
436:	learn: 0.0313509	total: 195ms	remaining: 252ms
437:	learn: 0.0312688	total: 196ms	remaining: 251ms
438:	learn: 0.0312315	total: 196ms	remaining: 250ms
439:	learn: 0.0311244	total: 196ms	remaining: 250ms
440:	learn: 0.0310498	total: 196ms	remaining: 249ms
441:	learn: 0.0309974	total: 197ms	remaining: 248ms
442:	learn: 0.0309142	total: 197ms	remaining: 248ms
443:	learn: 0.0308332	total: 197ms	remaining: 247ms
444:	learn: 0.0307685	total: 198ms	remaining: 247ms
445:	learn: 

987:	learn: 0.0110517	total: 381ms	remaining: 4.63ms
988:	learn: 0.0110451	total: 381ms	remaining: 4.24ms
989:	learn: 0.0110276	total: 381ms	remaining: 3.85ms
990:	learn: 0.0110065	total: 382ms	remaining: 3.47ms
991:	learn: 0.0109902	total: 382ms	remaining: 3.08ms
992:	learn: 0.0109736	total: 382ms	remaining: 2.69ms
993:	learn: 0.0109543	total: 383ms	remaining: 2.31ms
994:	learn: 0.0109334	total: 383ms	remaining: 1.92ms
995:	learn: 0.0109177	total: 383ms	remaining: 1.54ms
996:	learn: 0.0109001	total: 384ms	remaining: 1.15ms
997:	learn: 0.0108859	total: 384ms	remaining: 769us
998:	learn: 0.0108635	total: 384ms	remaining: 384us
999:	learn: 0.0108523	total: 384ms	remaining: 0us


## Predicting the result set

In [10]:
y_pred = classifier.predict(X_test)
y_pred

array([0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1,
       1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 1, 0])

In [11]:
np.concatenate((y_test.reshape(len(y_pred), 1), y_pred.reshape(len(y_test), 1)), axis=1)

array([[0, 0],
       [0, 0],
       [1, 1],
       [1, 1],
       [0, 0],
       [0, 0],
       [0, 0],
       [1, 1],
       [0, 0],
       [0, 0],
       [1, 1],
       [0, 0],
       [1, 1],
       [0, 0],
       [0, 0],
       [0, 0],
       [1, 1],
       [1, 1],
       [1, 1],
       [0, 0],
       [0, 0],
       [0, 0],
       [1, 1],
       [0, 0],
       [1, 1],
       [1, 1],
       [0, 0],
       [0, 0],
       [0, 0],
       [1, 1],
       [0, 0],
       [1, 1],
       [1, 1],
       [0, 0],
       [0, 0],
       [0, 0],
       [1, 1],
       [1, 1],
       [0, 0],
       [1, 1],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [1, 1],
       [0, 0],
       [0, 0],
       [1, 1],
       [0, 0],
       [1, 1],
       [0, 0],
       [0, 0],
       [0, 0],
       [1, 1],
       [0, 1],
       [0, 0],
       [1, 1],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0,

In [12]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)

array([[84,  3],
       [ 0, 50]])

In [13]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

0.9781021897810219

## K-fold validation

In [14]:
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator=classifier, X=X_train, y=y_train, cv=10)
accuracies

Learning rate set to 0.007604
0:	learn: 0.6773604	total: 338us	remaining: 338ms
1:	learn: 0.6638264	total: 682us	remaining: 340ms
2:	learn: 0.6487767	total: 941us	remaining: 313ms
3:	learn: 0.6331717	total: 1.21ms	remaining: 302ms
4:	learn: 0.6208046	total: 1.53ms	remaining: 304ms
5:	learn: 0.6054732	total: 1.86ms	remaining: 309ms
6:	learn: 0.5903624	total: 2.16ms	remaining: 306ms
7:	learn: 0.5763343	total: 2.44ms	remaining: 303ms
8:	learn: 0.5653778	total: 2.74ms	remaining: 301ms
9:	learn: 0.5531434	total: 3.02ms	remaining: 299ms
10:	learn: 0.5417318	total: 3.34ms	remaining: 300ms
11:	learn: 0.5322945	total: 3.55ms	remaining: 292ms
12:	learn: 0.5185135	total: 3.81ms	remaining: 289ms
13:	learn: 0.5075524	total: 4.74ms	remaining: 334ms
14:	learn: 0.4967003	total: 5.01ms	remaining: 329ms
15:	learn: 0.4866503	total: 5.23ms	remaining: 322ms
16:	learn: 0.4758187	total: 5.55ms	remaining: 321ms
17:	learn: 0.4667133	total: 5.84ms	remaining: 318ms
18:	learn: 0.4566130	total: 6.13ms	remaining: 3

491:	learn: 0.0264702	total: 152ms	remaining: 157ms
492:	learn: 0.0264323	total: 153ms	remaining: 157ms
493:	learn: 0.0263543	total: 153ms	remaining: 157ms
494:	learn: 0.0263241	total: 153ms	remaining: 156ms
495:	learn: 0.0262401	total: 154ms	remaining: 156ms
496:	learn: 0.0261908	total: 154ms	remaining: 156ms
497:	learn: 0.0261554	total: 154ms	remaining: 155ms
498:	learn: 0.0261014	total: 154ms	remaining: 155ms
499:	learn: 0.0260563	total: 155ms	remaining: 155ms
500:	learn: 0.0259843	total: 155ms	remaining: 154ms
501:	learn: 0.0259259	total: 155ms	remaining: 154ms
502:	learn: 0.0258648	total: 156ms	remaining: 154ms
503:	learn: 0.0258225	total: 156ms	remaining: 154ms
504:	learn: 0.0257677	total: 156ms	remaining: 153ms
505:	learn: 0.0257054	total: 157ms	remaining: 153ms
506:	learn: 0.0256221	total: 157ms	remaining: 153ms
507:	learn: 0.0255572	total: 157ms	remaining: 152ms
508:	learn: 0.0254995	total: 157ms	remaining: 152ms
509:	learn: 0.0254379	total: 158ms	remaining: 152ms
510:	learn: 

86:	learn: 0.1508542	total: 26.2ms	remaining: 275ms
87:	learn: 0.1492654	total: 26.6ms	remaining: 276ms
88:	learn: 0.1476988	total: 26.9ms	remaining: 276ms
89:	learn: 0.1462374	total: 27.2ms	remaining: 275ms
90:	learn: 0.1446420	total: 27.5ms	remaining: 275ms
91:	learn: 0.1428684	total: 27.8ms	remaining: 274ms
92:	learn: 0.1409876	total: 28.1ms	remaining: 274ms
93:	learn: 0.1390318	total: 28.4ms	remaining: 273ms
94:	learn: 0.1375344	total: 28.6ms	remaining: 273ms
95:	learn: 0.1362877	total: 28.9ms	remaining: 272ms
96:	learn: 0.1349103	total: 29.2ms	remaining: 272ms
97:	learn: 0.1330770	total: 29.5ms	remaining: 271ms
98:	learn: 0.1314734	total: 29.8ms	remaining: 271ms
99:	learn: 0.1302147	total: 30ms	remaining: 270ms
100:	learn: 0.1287860	total: 30.3ms	remaining: 270ms
101:	learn: 0.1273032	total: 30.6ms	remaining: 269ms
102:	learn: 0.1261246	total: 31.6ms	remaining: 276ms
103:	learn: 0.1246874	total: 32ms	remaining: 275ms
104:	learn: 0.1235693	total: 32.4ms	remaining: 276ms
105:	learn:

688:	learn: 0.0157023	total: 216ms	remaining: 97.3ms
689:	learn: 0.0156704	total: 216ms	remaining: 97.1ms
690:	learn: 0.0156370	total: 216ms	remaining: 96.8ms
691:	learn: 0.0156103	total: 217ms	remaining: 96.4ms
692:	learn: 0.0155827	total: 217ms	remaining: 96.1ms
693:	learn: 0.0155672	total: 217ms	remaining: 95.8ms
694:	learn: 0.0155505	total: 218ms	remaining: 95.5ms
695:	learn: 0.0155160	total: 218ms	remaining: 95.1ms
696:	learn: 0.0154661	total: 218ms	remaining: 94.8ms
697:	learn: 0.0154348	total: 218ms	remaining: 94.5ms
698:	learn: 0.0154119	total: 219ms	remaining: 94.1ms
699:	learn: 0.0153691	total: 219ms	remaining: 93.8ms
700:	learn: 0.0153285	total: 219ms	remaining: 93.5ms
701:	learn: 0.0153146	total: 220ms	remaining: 93.2ms
702:	learn: 0.0152864	total: 220ms	remaining: 92.9ms
703:	learn: 0.0152710	total: 220ms	remaining: 92.6ms
704:	learn: 0.0152473	total: 220ms	remaining: 92.2ms
705:	learn: 0.0152192	total: 221ms	remaining: 91.9ms
706:	learn: 0.0151922	total: 221ms	remaining: 

279:	learn: 0.0509264	total: 84.2ms	remaining: 216ms
280:	learn: 0.0506861	total: 84.6ms	remaining: 217ms
281:	learn: 0.0504780	total: 84.9ms	remaining: 216ms
282:	learn: 0.0502109	total: 85.2ms	remaining: 216ms
283:	learn: 0.0500346	total: 85.5ms	remaining: 216ms
284:	learn: 0.0498511	total: 85.8ms	remaining: 215ms
285:	learn: 0.0496464	total: 86ms	remaining: 215ms
286:	learn: 0.0494894	total: 86.3ms	remaining: 214ms
287:	learn: 0.0493251	total: 86.6ms	remaining: 214ms
288:	learn: 0.0491333	total: 86.9ms	remaining: 214ms
289:	learn: 0.0489667	total: 87.1ms	remaining: 213ms
290:	learn: 0.0487398	total: 87.5ms	remaining: 213ms
291:	learn: 0.0485279	total: 87.7ms	remaining: 213ms
292:	learn: 0.0483166	total: 88ms	remaining: 212ms
293:	learn: 0.0480875	total: 88.3ms	remaining: 212ms
294:	learn: 0.0479526	total: 88.6ms	remaining: 212ms
295:	learn: 0.0478322	total: 88.8ms	remaining: 211ms
296:	learn: 0.0477186	total: 89.1ms	remaining: 211ms
297:	learn: 0.0476041	total: 89.4ms	remaining: 211

879:	learn: 0.0137402	total: 273ms	remaining: 37.2ms
880:	learn: 0.0137174	total: 274ms	remaining: 37ms
881:	learn: 0.0136954	total: 274ms	remaining: 36.6ms
882:	learn: 0.0136714	total: 274ms	remaining: 36.3ms
883:	learn: 0.0136449	total: 274ms	remaining: 36ms
884:	learn: 0.0136221	total: 275ms	remaining: 35.7ms
885:	learn: 0.0135934	total: 275ms	remaining: 35.4ms
886:	learn: 0.0135769	total: 275ms	remaining: 35.1ms
887:	learn: 0.0135554	total: 276ms	remaining: 34.8ms
888:	learn: 0.0135416	total: 276ms	remaining: 34.5ms
889:	learn: 0.0135265	total: 276ms	remaining: 34.1ms
890:	learn: 0.0135000	total: 277ms	remaining: 33.8ms
891:	learn: 0.0134914	total: 277ms	remaining: 33.5ms
892:	learn: 0.0134698	total: 277ms	remaining: 33.2ms
893:	learn: 0.0134372	total: 277ms	remaining: 32.9ms
894:	learn: 0.0134069	total: 278ms	remaining: 32.6ms
895:	learn: 0.0133896	total: 278ms	remaining: 32.3ms
896:	learn: 0.0133650	total: 278ms	remaining: 31.9ms
897:	learn: 0.0133507	total: 278ms	remaining: 31.6

456:	learn: 0.0320446	total: 137ms	remaining: 163ms
457:	learn: 0.0319648	total: 138ms	remaining: 163ms
458:	learn: 0.0319083	total: 138ms	remaining: 162ms
459:	learn: 0.0317704	total: 138ms	remaining: 162ms
460:	learn: 0.0317378	total: 138ms	remaining: 162ms
461:	learn: 0.0316384	total: 139ms	remaining: 162ms
462:	learn: 0.0315639	total: 139ms	remaining: 161ms
463:	learn: 0.0314639	total: 139ms	remaining: 161ms
464:	learn: 0.0313955	total: 140ms	remaining: 161ms
465:	learn: 0.0313108	total: 140ms	remaining: 160ms
466:	learn: 0.0312397	total: 140ms	remaining: 160ms
467:	learn: 0.0311325	total: 140ms	remaining: 160ms
468:	learn: 0.0311073	total: 141ms	remaining: 159ms
469:	learn: 0.0310334	total: 141ms	remaining: 159ms
470:	learn: 0.0309433	total: 141ms	remaining: 159ms
471:	learn: 0.0308436	total: 141ms	remaining: 158ms
472:	learn: 0.0307675	total: 142ms	remaining: 158ms
473:	learn: 0.0307334	total: 142ms	remaining: 158ms
474:	learn: 0.0306390	total: 142ms	remaining: 157ms
475:	learn: 

45:	learn: 0.2754515	total: 14.7ms	remaining: 305ms
46:	learn: 0.2710946	total: 15.2ms	remaining: 309ms
47:	learn: 0.2663681	total: 15.5ms	remaining: 308ms
48:	learn: 0.2613521	total: 15.8ms	remaining: 307ms
49:	learn: 0.2568128	total: 16.1ms	remaining: 306ms
50:	learn: 0.2528889	total: 16.4ms	remaining: 305ms
51:	learn: 0.2494762	total: 16.7ms	remaining: 304ms
52:	learn: 0.2453113	total: 16.9ms	remaining: 303ms
53:	learn: 0.2410372	total: 17.2ms	remaining: 301ms
54:	learn: 0.2374781	total: 17.5ms	remaining: 300ms
55:	learn: 0.2349308	total: 17.8ms	remaining: 300ms
56:	learn: 0.2310005	total: 18.1ms	remaining: 299ms
57:	learn: 0.2269999	total: 18.4ms	remaining: 298ms
58:	learn: 0.2248778	total: 18.7ms	remaining: 298ms
59:	learn: 0.2215807	total: 19ms	remaining: 297ms
60:	learn: 0.2179338	total: 19.3ms	remaining: 297ms
61:	learn: 0.2159398	total: 19.6ms	remaining: 296ms
62:	learn: 0.2131213	total: 19.8ms	remaining: 295ms
63:	learn: 0.2097451	total: 20.1ms	remaining: 295ms
64:	learn: 0.2

679:	learn: 0.0173972	total: 204ms	remaining: 96ms
680:	learn: 0.0173682	total: 204ms	remaining: 95.7ms
681:	learn: 0.0173270	total: 205ms	remaining: 95.4ms
682:	learn: 0.0173098	total: 205ms	remaining: 95.1ms
683:	learn: 0.0172729	total: 205ms	remaining: 94.8ms
684:	learn: 0.0172360	total: 206ms	remaining: 94.6ms
685:	learn: 0.0172038	total: 206ms	remaining: 94.2ms
686:	learn: 0.0171532	total: 206ms	remaining: 94ms
687:	learn: 0.0171281	total: 207ms	remaining: 93.7ms
688:	learn: 0.0170909	total: 207ms	remaining: 93.4ms
689:	learn: 0.0170582	total: 207ms	remaining: 93ms
690:	learn: 0.0170355	total: 207ms	remaining: 92.7ms
691:	learn: 0.0170135	total: 208ms	remaining: 92.4ms
692:	learn: 0.0170041	total: 208ms	remaining: 92.1ms
693:	learn: 0.0169873	total: 208ms	remaining: 91.8ms
694:	learn: 0.0169497	total: 209ms	remaining: 91.5ms
695:	learn: 0.0169119	total: 209ms	remaining: 91.2ms
696:	learn: 0.0168812	total: 209ms	remaining: 90.9ms
697:	learn: 0.0168250	total: 209ms	remaining: 90.6ms

279:	learn: 0.0547622	total: 82.7ms	remaining: 213ms
280:	learn: 0.0545280	total: 83ms	remaining: 212ms
281:	learn: 0.0543814	total: 83.3ms	remaining: 212ms
282:	learn: 0.0542565	total: 83.6ms	remaining: 212ms
283:	learn: 0.0540427	total: 83.9ms	remaining: 212ms
284:	learn: 0.0538988	total: 84.2ms	remaining: 211ms
285:	learn: 0.0537271	total: 84.5ms	remaining: 211ms
286:	learn: 0.0535595	total: 84.8ms	remaining: 211ms
287:	learn: 0.0533584	total: 85.1ms	remaining: 210ms
288:	learn: 0.0530962	total: 85.4ms	remaining: 210ms
289:	learn: 0.0529680	total: 85.7ms	remaining: 210ms
290:	learn: 0.0528463	total: 86ms	remaining: 209ms
291:	learn: 0.0526462	total: 86.3ms	remaining: 209ms
292:	learn: 0.0523800	total: 86.6ms	remaining: 209ms
293:	learn: 0.0522390	total: 86.9ms	remaining: 209ms
294:	learn: 0.0521312	total: 87.2ms	remaining: 208ms
295:	learn: 0.0518801	total: 87.5ms	remaining: 208ms
296:	learn: 0.0516562	total: 87.8ms	remaining: 208ms
297:	learn: 0.0515504	total: 88.1ms	remaining: 207

868:	learn: 0.0152560	total: 269ms	remaining: 40.6ms
869:	learn: 0.0152149	total: 270ms	remaining: 40.3ms
870:	learn: 0.0151999	total: 270ms	remaining: 40ms
871:	learn: 0.0151654	total: 271ms	remaining: 39.7ms
872:	learn: 0.0151311	total: 271ms	remaining: 39.4ms
873:	learn: 0.0150995	total: 271ms	remaining: 39.1ms
874:	learn: 0.0150715	total: 271ms	remaining: 38.8ms
875:	learn: 0.0150546	total: 272ms	remaining: 38.5ms
876:	learn: 0.0150133	total: 272ms	remaining: 38.1ms
877:	learn: 0.0149780	total: 272ms	remaining: 37.8ms
878:	learn: 0.0149575	total: 273ms	remaining: 37.5ms
879:	learn: 0.0149324	total: 273ms	remaining: 37.2ms
880:	learn: 0.0149005	total: 273ms	remaining: 36.9ms
881:	learn: 0.0148568	total: 273ms	remaining: 36.6ms
882:	learn: 0.0148284	total: 274ms	remaining: 36.3ms
883:	learn: 0.0147996	total: 274ms	remaining: 35.9ms
884:	learn: 0.0147821	total: 274ms	remaining: 35.6ms
885:	learn: 0.0147596	total: 275ms	remaining: 35.3ms
886:	learn: 0.0147478	total: 275ms	remaining: 35

466:	learn: 0.0257776	total: 141ms	remaining: 161ms
467:	learn: 0.0256892	total: 141ms	remaining: 161ms
468:	learn: 0.0256142	total: 142ms	remaining: 160ms
469:	learn: 0.0255572	total: 142ms	remaining: 160ms
470:	learn: 0.0254759	total: 142ms	remaining: 160ms
471:	learn: 0.0253878	total: 143ms	remaining: 159ms
472:	learn: 0.0253303	total: 143ms	remaining: 159ms
473:	learn: 0.0252795	total: 143ms	remaining: 159ms
474:	learn: 0.0252231	total: 143ms	remaining: 158ms
475:	learn: 0.0251779	total: 144ms	remaining: 158ms
476:	learn: 0.0250670	total: 144ms	remaining: 158ms
477:	learn: 0.0250195	total: 144ms	remaining: 157ms
478:	learn: 0.0249611	total: 144ms	remaining: 157ms
479:	learn: 0.0249011	total: 145ms	remaining: 157ms
480:	learn: 0.0248275	total: 145ms	remaining: 156ms
481:	learn: 0.0247467	total: 145ms	remaining: 156ms
482:	learn: 0.0246974	total: 146ms	remaining: 156ms
483:	learn: 0.0246420	total: 146ms	remaining: 156ms
484:	learn: 0.0245653	total: 146ms	remaining: 155ms
485:	learn: 

57:	learn: 0.2300178	total: 17.8ms	remaining: 289ms
58:	learn: 0.2269642	total: 18.3ms	remaining: 293ms
59:	learn: 0.2241269	total: 18.6ms	remaining: 292ms
60:	learn: 0.2204805	total: 18.9ms	remaining: 292ms
61:	learn: 0.2177853	total: 19.2ms	remaining: 291ms
62:	learn: 0.2148270	total: 19.5ms	remaining: 290ms
63:	learn: 0.2123349	total: 19.8ms	remaining: 289ms
64:	learn: 0.2102908	total: 20.1ms	remaining: 289ms
65:	learn: 0.2078424	total: 20.5ms	remaining: 290ms
66:	learn: 0.2053674	total: 20.7ms	remaining: 289ms
67:	learn: 0.2023030	total: 21ms	remaining: 288ms
68:	learn: 0.1992284	total: 21.3ms	remaining: 287ms
69:	learn: 0.1963580	total: 21.6ms	remaining: 287ms
70:	learn: 0.1933913	total: 21.9ms	remaining: 286ms
71:	learn: 0.1904660	total: 22.2ms	remaining: 286ms
72:	learn: 0.1878693	total: 22.5ms	remaining: 286ms
73:	learn: 0.1857742	total: 22.8ms	remaining: 286ms
74:	learn: 0.1833304	total: 23.1ms	remaining: 285ms
75:	learn: 0.1812933	total: 23.4ms	remaining: 285ms
76:	learn: 0.1

685:	learn: 0.0184503	total: 206ms	remaining: 94.1ms
686:	learn: 0.0183987	total: 206ms	remaining: 93.9ms
687:	learn: 0.0183376	total: 206ms	remaining: 93.6ms
688:	learn: 0.0183121	total: 207ms	remaining: 93.3ms
689:	learn: 0.0182730	total: 207ms	remaining: 93ms
690:	learn: 0.0182323	total: 207ms	remaining: 92.7ms
691:	learn: 0.0181905	total: 207ms	remaining: 92.3ms
692:	learn: 0.0181707	total: 208ms	remaining: 92ms
693:	learn: 0.0181226	total: 208ms	remaining: 91.7ms
694:	learn: 0.0180838	total: 208ms	remaining: 91.4ms
695:	learn: 0.0180263	total: 209ms	remaining: 91.1ms
696:	learn: 0.0179912	total: 209ms	remaining: 90.8ms
697:	learn: 0.0179544	total: 209ms	remaining: 90.5ms
698:	learn: 0.0179254	total: 210ms	remaining: 90.5ms
699:	learn: 0.0179088	total: 211ms	remaining: 90.2ms
700:	learn: 0.0178617	total: 211ms	remaining: 89.9ms
701:	learn: 0.0178135	total: 211ms	remaining: 89.6ms
702:	learn: 0.0177736	total: 211ms	remaining: 89.3ms
703:	learn: 0.0177440	total: 212ms	remaining: 89ms

249:	learn: 0.0610301	total: 73.6ms	remaining: 221ms
250:	learn: 0.0608043	total: 74.1ms	remaining: 221ms
251:	learn: 0.0605661	total: 74.4ms	remaining: 221ms
252:	learn: 0.0602962	total: 74.7ms	remaining: 221ms
253:	learn: 0.0600784	total: 75ms	remaining: 220ms
254:	learn: 0.0598072	total: 75.3ms	remaining: 220ms
255:	learn: 0.0596158	total: 75.7ms	remaining: 220ms
256:	learn: 0.0594718	total: 76ms	remaining: 220ms
257:	learn: 0.0592015	total: 76.4ms	remaining: 220ms
258:	learn: 0.0590225	total: 76.7ms	remaining: 219ms
259:	learn: 0.0588533	total: 77ms	remaining: 219ms
260:	learn: 0.0586080	total: 77.3ms	remaining: 219ms
261:	learn: 0.0584062	total: 77.6ms	remaining: 219ms
262:	learn: 0.0580915	total: 77.9ms	remaining: 218ms
263:	learn: 0.0579161	total: 78.2ms	remaining: 218ms
264:	learn: 0.0577250	total: 78.5ms	remaining: 218ms
265:	learn: 0.0574617	total: 78.8ms	remaining: 217ms
266:	learn: 0.0572474	total: 79.1ms	remaining: 217ms
267:	learn: 0.0569550	total: 79.4ms	remaining: 217ms

863:	learn: 0.0150770	total: 262ms	remaining: 41.2ms
864:	learn: 0.0150525	total: 262ms	remaining: 41ms
865:	learn: 0.0150460	total: 263ms	remaining: 40.6ms
866:	learn: 0.0150109	total: 263ms	remaining: 40.3ms
867:	learn: 0.0149858	total: 263ms	remaining: 40ms
868:	learn: 0.0149543	total: 264ms	remaining: 39.8ms
869:	learn: 0.0149346	total: 264ms	remaining: 39.5ms
870:	learn: 0.0149150	total: 264ms	remaining: 39.2ms
871:	learn: 0.0148698	total: 265ms	remaining: 38.9ms
872:	learn: 0.0148342	total: 265ms	remaining: 38.6ms
873:	learn: 0.0147997	total: 265ms	remaining: 38.3ms
874:	learn: 0.0147770	total: 266ms	remaining: 38ms
875:	learn: 0.0147482	total: 266ms	remaining: 37.7ms
876:	learn: 0.0147191	total: 266ms	remaining: 37.4ms
877:	learn: 0.0146780	total: 267ms	remaining: 37.1ms
878:	learn: 0.0146435	total: 267ms	remaining: 36.8ms
879:	learn: 0.0146143	total: 267ms	remaining: 36.5ms
880:	learn: 0.0146059	total: 268ms	remaining: 36.2ms
881:	learn: 0.0145786	total: 268ms	remaining: 35.9ms

452:	learn: 0.0315071	total: 137ms	remaining: 165ms
453:	learn: 0.0314107	total: 137ms	remaining: 165ms
454:	learn: 0.0313315	total: 138ms	remaining: 165ms
455:	learn: 0.0312492	total: 138ms	remaining: 165ms
456:	learn: 0.0311656	total: 138ms	remaining: 164ms
457:	learn: 0.0310618	total: 138ms	remaining: 164ms
458:	learn: 0.0309801	total: 139ms	remaining: 164ms
459:	learn: 0.0309041	total: 139ms	remaining: 163ms
460:	learn: 0.0308287	total: 139ms	remaining: 163ms
461:	learn: 0.0307562	total: 140ms	remaining: 163ms
462:	learn: 0.0306701	total: 140ms	remaining: 162ms
463:	learn: 0.0305971	total: 140ms	remaining: 162ms
464:	learn: 0.0305369	total: 141ms	remaining: 162ms
465:	learn: 0.0304760	total: 141ms	remaining: 162ms
466:	learn: 0.0303879	total: 142ms	remaining: 162ms
467:	learn: 0.0302833	total: 142ms	remaining: 161ms
468:	learn: 0.0301817	total: 142ms	remaining: 161ms
469:	learn: 0.0301433	total: 142ms	remaining: 161ms
470:	learn: 0.0300948	total: 143ms	remaining: 160ms
471:	learn: 

array([0.90909091, 0.94545455, 0.96363636, 0.98181818, 0.96363636,
       1.        , 0.96296296, 0.96296296, 1.        , 0.96296296])

In [15]:
accuracies.mean(), accuracies.std().round(2)

(np.float64(0.9652525252525253), np.float64(0.03))

In [16]:
accuracies

array([0.90909091, 0.94545455, 0.96363636, 0.98181818, 0.96363636,
       1.        , 0.96296296, 0.96296296, 1.        , 0.96296296])